# fly.toml app configuration file generated for devcartify-learning-app on 2026-02-16T12:52:26+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'devcartify-learning-app'
primary_region = 'fra'

[build]

[deploy]
  release_command = "npx prisma db push --accept-data-loss"

[env]
  PORT = '3000'
  SCOPES = 'read_fulfillments,read_merchant_managed_fulfillment_orders,read_orders,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders'
  SHOPIFY_API_KEY = 'b70785f5a282bd9d6b6700f177d04928'
  SHOPIFY_APP_URL = 'https://devcartify-learning-app.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
