# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e6e32e2eae587c797f8fe3a832b27a40"
name = "devcartify-app"
application_url = "https://devcartify-app.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# These are the permissions needed to fulfill orders
scopes = "read_orders, write_orders, read_fulfillments, write_fulfillments, read_merchant_managed_fulfillment_orders, write_merchant_managed_fulfillment_orders"

[auth]
redirect_urls = [
  "https://devcartify-app.fly.dev/auth/callback",
  "https://devcartify-app.fly.dev/auth/shopify/callback",
  "https://devcartify-app.fly.dev/api/auth/callback"
]